name: Build and Deploy .NET Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish project
      run: dotnet publish --configuration Release --output ./output

    - name: Enable Debugging
      run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

    - name: Deploy to server
      env:
        CLICKHOUSE_CONNECTION_STRING: ${{ secrets.CLICKHOUSE_CONNECTION_STRING }}
      run: |
        # Utilisez la chaîne de connexion dans votre script de déploiement
        echo "Deploying using connection string: $CLICKHOUSE_CONNECTION_STRING"
